default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: siemakuba
  password:

development:
  <<: *default
  database: gat_development

test:
  <<: *default
  database: gat_test

production:
  <<: *default
  database: gat_production
  username: <%= ENV['GAT_DATABASE_USERNAME'] %>
  password: <%= ENV['GAT_DATABASE_PASSWORD'] %>
